// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxMvlw-hgX-qWf1CsexZODGnrcRx2o-k',
    appId: '1:853052114283:web:dce15af5df5eb5e951782e',
    messagingSenderId: '853052114283',
    projectId: 'smartkhrishi',
    authDomain: 'smartkhrishi.firebaseapp.com',
    storageBucket: 'smartkhrishi.firebasestorage.app',
    measurementId: 'G-H7M3VKH2SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGqgmhj7tQV_E2n1s1H_LTumDoygL3x8',
    appId: '1:853052114283:android:d15e9c119ed5ec7951782e',
    messagingSenderId: '853052114283',
    projectId: 'smartkhrishi',
    storageBucket: 'smartkhrishi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4s4bLjiSLA1u_wlVHBEJAl79h7MrlW-I',
    appId: '1:853052114283:ios:5b787c31fa4c87ef51782e',
    messagingSenderId: '853052114283',
    projectId: 'smartkhrishi',
    storageBucket: 'smartkhrishi.firebasestorage.app',
    iosBundleId: 'com.example.plantHealth',
  );
}
